"""Standalone static HTML dashboard for a pyreplab experiment run.

The dashboard turns three optional sources into a single self-contained HTML
file (all CSS/JS/data embedded, no network, no CDN, no framework):

* ``dataset_path``   -- the leakage-safe deterministic JSONL corpus produced
  by :mod:`pyreplab_harness.dataset` (required input).
* ``metrics_path``   -- optional ``metrics.json`` emitted by
  :mod:`pyreplab_harness.outcome_model` (per-split metric bundles, optional
  binned calibration data).
* ``baselines_path`` -- optional allocator baseline JSON (strategy aggregate
  table).

Public API
----------
``build_dashboard_data(dataset_path, metrics_path=None, baselines_path=None)``
  -> dict  (all embedded data plus precomputed unfiltered aggregates)
``render_dashboard(data)``
  -> str   (the complete standalone HTML document)
``write_dashboard(...)``
  -> summary dict (atomic temp-file + replace write)
plus a module CLI (``python -m pyreplab_harness.dashboard``).

Privacy whitelist (SHIP-BLOCKING)
---------------------------------
Every embedded row is rebuilt from an explicit whitelist.  The following never
enter the dashboard: full prompts/contracts, raw ``public_metadata`` dicts,
``model_input.text``, final answer text, verifier diagnostics, oracle/private
data, any ``*_ref``/workspace/path value, raw Pi events, host/model config and
task-level model posterior samples.  Allowed: IDs, family/template/version/
seed/difficulty, policy, split, verified success/failure code and verifier
IDs, usage counters, message/tool counts, final text length and *flattened*
finite numeric/bool public metadata (taken from ``model_input.public_metadata``
when present).  A prompt preview is allowed but is capped at
:data:`PROMPT_PREVIEW_LIMIT` characters.

Robustness
----------
The dataset is required: a missing file raises ``FileNotFoundError`` and a
malformed line raises ``ValueError`` with its path.  Rows that are unusable
(missing identity or label keys) are skipped and reported as warnings.  The
optional ``metrics`` and ``baselines`` inputs degrade to explicit
``missing``/``malformed`` states instead of crashing, and never embed raw
optional files (only whitelisted numeric aggregates).

Determinism
-----------
All iteration is explicitly sorted, no timestamps or randomness are embedded,
and JSON is serialized with ``sort_keys=True``.  Identical inputs therefore
produce byte-identical HTML.

Rendering model
---------------
The HTML contains a fully rendered *unfiltered* state generated by this module
(so the aggregate tables are testable in the static markup), plus an embedded
JSON payload.  The inline JavaScript mirrors these aggregation functions and
re-renders every row-derived section synchronously when the native checkboxes
in the filter bar change.  JS never uses ``innerHTML`` with untrusted values:
dynamic content is built with ``textContent``/``createElement``, and the
embedded JSON escapes ``<``/``>``/``&`` so ``</script>`` cannot break out.
"""

from __future__ import annotations

import argparse
import html
import json
import math
import os
import sys
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any, Iterable

from .dataset import flatten_public_metadata

#: Attempt-browser display cap (rows rendered per filter state).
BROWSER_ROW_CAP = 500
#: Prompt preview character cap.
PROMPT_PREVIEW_LIMIT = 120
#: Small-sample warning threshold (attempts).
_SMALL_SAMPLE_THRESHOLD = 30
_SPLIT_ORDER = ("train", "validation", "test")

#: Colors for the canonical experiment policies; any other policy is assigned
#: a deterministic palette color by sorted policy id.
_POLICY_COLORS = {"direct": "#1565C0", "deliberate": "#E65100"}
_PALETTE = (
    "#1565C0", "#E65100", "#2E7D32", "#6A1B9A", "#00695C",
    "#AD1457", "#37474F", "#5D4037", "#4527A0", "#1B5E20",
)

_MODEL_METRIC_KEYS = (
    "log_loss", "brier", "accuracy_05", "ece", "mean_posterior_std",
)

_BASELINE_SUCCESS_ALIASES = (
    "success_rate", "verified_success_rate", "success", "rate",
    "accuracy", "verified_success",
)
_BASELINE_N_ALIASES = ("n", "attempts", "tasks", "count", "num_attempts", "rows")
_BASELINE_TOKENS_ALIASES = (
    "mean_tokens", "avg_tokens", "mean_total_tokens", "total_tokens", "tokens",
)
_BASELINE_TOOLS_ALIASES = ("mean_tool_calls", "avg_tool_calls", "tool_calls")
_BASELINE_MSGS_ALIASES = (
    "mean_messages", "avg_messages", "assistant_messages", "messages",
)


# ---------------------------------------------------------------------------
# Small coercion / formatting helpers
# ---------------------------------------------------------------------------
def _s(value: Any) -> str | None:
    return None if value is None else str(value)


def _i(value: Any) -> int:
    if isinstance(value, bool):
        return 0
    if isinstance(value, int):
        return value
    if isinstance(value, float) and math.isfinite(value):
        return int(value)
    return 0


def _finite_float(value: Any) -> float | None:
    if value is None or isinstance(value, bool):
        return None
    if isinstance(value, (int, float)):
        value = float(value)
        return value if math.isfinite(value) else None
    return None


def _preview(value: Any) -> str | None:
    """Sanitized prompt preview, whitespace-collapsed, capped at 120 chars."""
    if value is None:
        return None
    collapsed = " ".join(str(value).split())
    if len(collapsed) > PROMPT_PREVIEW_LIMIT:
        return collapsed[:PROMPT_PREVIEW_LIMIT] + "…"
    return collapsed or None


def _esc(value: Any) -> str:
    """HTML-escape an untrusted value for static markup."""
    return html.escape("" if value is None else str(value), quote=True)


def _fmt_pct(rate: float | None) -> str:
    return "—" if rate is None else f"{rate * 100:.1f}%"


def _fmt_num(value: float | None, digits: int = 1) -> str:
    return "—" if value is None else f"{value:.{digits}f}"


def _fmt_int(value: float | None) -> str:
    return "—" if value is None else f"{value:.0f}"


def _mean(values: list[float]) -> float | None:
    return sum(values) / len(values) if values else None


def _pop_std(values: list[float]) -> float | None:
    n = len(values)
    if n == 0:
        return None
    if n == 1:
        return 0.0
    mean = sum(values) / n
    return math.sqrt(sum((v - mean) ** 2 for v in values) / n)


def _min_max(values: list[float]) -> tuple[float | None, float | None]:
    if not values:
        return None, None
    return min(values), max(values)


def _json_script_safe(value: Any) -> str:
    """Serialize ``value`` so it is safe inside a ``<script>`` element.

    ``ensure_ascii=True`` already escapes every non-ASCII character; the extra
    replaces neutralise the three ASCII characters that can terminate or
    corrupt the script element even inside a string literal.
    """
    payload = json.dumps(value, ensure_ascii=True, sort_keys=True)
    return (
        payload.replace("<", "\\u003c")
        .replace(">", "\\u003e")
        .replace("&", "\\u0026")
    )


# ---------------------------------------------------------------------------
# Dataset loading and per-row privacy whitelist
# ---------------------------------------------------------------------------
def _load_dataset_rows(dataset_path: str | Path) -> tuple[list[dict[str, Any]], int]:
    """Load deterministic JSONL rows, raising on missing file / bad JSON.

    Returns ``(rows, skipped)`` where ``skipped`` counts lines that were valid
    JSON but unusable (missing identity or label keys).  A malformed JSON line
    raises ``ValueError`` with the file path and line number.
    """
    path = Path(dataset_path).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(f"dataset does not exist: {path}")
    rows: list[dict[str, Any]] = []
    skipped = 0
    with path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError as error:
                raise ValueError(f"malformed JSON at {path}:{line_number}: {error}") from error
            if not isinstance(row, dict):
                skipped += 1
                continue
            if not (
                isinstance(row.get("task_id"), str)
                and isinstance(row.get("policy_id"), str)
            ):
                skipped += 1
                continue
            label = row.get("verified_success")
            if label is True or label is False:
                pass
            elif label in (0, 1):
                row["verified_success"] = bool(label)
            else:
                skipped += 1
                continue
            rows.append(row)
    return rows, skipped


def _sanitize_usage(usage: Any) -> dict[str, int]:
    """Whitelisted usage counters: integer values only."""
    if not isinstance(usage, dict):
        return {}
    out: dict[str, int] = {}
    for key, value in usage.items():
        if isinstance(value, bool):
            continue
        if isinstance(value, int):
            out[str(key)] = value
        elif isinstance(value, float) and math.isfinite(value) and value.is_integer():
            out[str(key)] = int(value)
    return out


def _sanitize_metadata(row: dict[str, Any]) -> dict[str, Any]:
    """Flattened finite numeric/bool public metadata (never the raw dict)."""
    model_input = row.get("model_input")
    flat = None
    if isinstance(model_input, dict) and isinstance(model_input.get("public_metadata"), dict):
        flat = model_input["public_metadata"]
    else:
        raw = row.get("public_metadata")
        if isinstance(raw, dict):
            flat = flatten_public_metadata(raw)
    if not isinstance(flat, dict):
        return {}
    cleaned: dict[str, Any] = {}
    for key, value in flat.items():
        if isinstance(value, bool):
            cleaned[str(key)] = value
        elif isinstance(value, int):
            cleaned[str(key)] = value
        elif isinstance(value, float) and math.isfinite(value):
            cleaned[str(key)] = value
    return cleaned


def _row_to_public(row: dict[str, Any]) -> dict[str, Any]:
    """Rebuild one dataset row from an explicit whitelist of allowed fields.

    Every key written below is individually allowed.  Forbidden content
    (full prompt/contract, raw metadata, model_input.text, paths, diagnostics,
    events, host/model config, posterior samples) can therefore never leak:
    unknown keys are simply never copied.
    """
    return {
        "task_id": _s(row.get("task_id")),
        "family": _s(row.get("family")),
        "template_id": _s(row.get("template_id")),
        "generator_version": _s(row.get("generator_version")),
        "seed": _i(row.get("seed")),
        "difficulty": _s(row.get("difficulty")),
        "prompt_preview": _preview(row.get("prompt")),
        "attempt_id": _s(row.get("attempt_id")),
        "policy_id": _s(row.get("policy_id")),
        "policy_version": _s(row.get("policy_version")),
        "split": _s(row.get("split")),
        "verified_success": bool(row.get("verified_success")),
        "failure_code": _s(row.get("failure_code")),
        "verifier_id": _s(row.get("verifier_id")),
        "verifier_version": _s(row.get("verifier_version")),
        "usage": _sanitize_usage(row.get("usage")),
        "assistant_message_count": _i(row.get("assistant_message_count")),
        "tool_call_count": _i(row.get("tool_call_count")),
        "final_text_length": _i(row.get("final_text_length")),
        "metadata": _sanitize_metadata(row),
    }


def total_tokens(row: dict[str, Any]) -> int:
    """Total token counter for a public row (``usage.total_tokens`` or sum)."""
    usage = row.get("usage") or {}
    total = usage.get("total_tokens")
    if isinstance(total, int) and not isinstance(total, bool):
        return total
    if isinstance(total, float) and total.is_integer():
        return int(total)
    return sum(
        value
        for value in usage.values()
        if isinstance(value, int) and not isinstance(value, bool)
    )


# ---------------------------------------------------------------------------
# Aggregation functions (pure Python; mirrored by the inline JavaScript)
# ---------------------------------------------------------------------------
def aggregate_gym(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Gym-health KPIs plus the family x policy success table."""
    total_rows = len(rows)
    task_ids = sorted({row["task_id"] for row in rows})
    total_tasks = len(task_ids)
    policies = sorted({row["policy_id"] for row in rows})
    families = sorted({row["family"] for row in rows})
    paired_tasks = 0
    for task_id in task_ids:
        present = {row["policy_id"] for row in rows if row["task_id"] == task_id}
        if len(present) >= 2:
            paired_tasks += 1
    success_count = sum(1 for row in rows if row["verified_success"])
    token_values = [total_tokens(row) for row in rows]
    cells: dict[tuple[str, str], dict[str, int]] = {}
    for row in rows:
        cell = cells.setdefault((row["family"], row["policy_id"]), {"n": 0, "success": 0})
        cell["n"] += 1
        cell["success"] += 1 if row["verified_success"] else 0
    family_policy: list[dict[str, Any]] = []
    for family in families:
        for policy in policies:
            cell = cells.get((family, policy))
            if cell is None:
                continue
            family_policy.append(
                {
                    "family": family,
                    "policy": policy,
                    "n": cell["n"],
                    "success": cell["success"],
                    "success_rate": (
                        cell["success"] / cell["n"] if cell["n"] else None
                    ),
                }
            )
    return {
        "total_rows": total_rows,
        "total_tasks": total_tasks,
        "paired_tasks": paired_tasks,
        "task_coverage": paired_tasks / total_tasks if total_tasks else None,
        "success_count": success_count,
        "overall_success_rate": success_count / total_rows if total_rows else None,
        "avg_total_tokens": _mean(token_values) if token_values else None,
        # Real paired-disagreement rate so the static Gym Health KPI is not "—".
        "disagreement_rate": policy_disagreement(rows)["disagreement_rate"],
        "policies": policies,
        "families": families,
        "family_policy": family_policy,
    }


def pair_policies(rows: list[dict[str, Any]]) -> tuple[str | None, str | None]:
    """The two policies compared in the disagreement matrix.

    The canonical experiment policies ``direct`` and ``deliberate`` map to
    slots A and B when present, matching the fixed direct=blue / deliberate=
    orange scheme.  Otherwise the two most frequent policies are used with ties
    broken deterministically by policy id.
    """
    counts = Counter(row["policy_id"] for row in rows)
    if not counts:
        return None, None
    ordered = sorted(counts.items(), key=lambda item: (-item[1], item[0]))
    available = [policy_id for policy_id, _count in ordered]
    policy_a = "direct" if "direct" in counts else available[0]
    if "deliberate" in counts and "deliberate" != policy_a:
        policy_b = "deliberate"
    else:
        rest = [policy_id for policy_id in available if policy_id != policy_a]
        policy_b = rest[0] if rest else None
    return policy_a, policy_b


def _task_policy_outcome(
    rows: list[dict[str, Any]], task_id: str | None, policy: str | None
) -> bool | None:
    """Representative outcome for one (task, policy): first attempt by id."""
    if task_id is None or policy is None:
        return None
    candidates = sorted(
        (
            row
            for row in rows
            if row["task_id"] == task_id and row["policy_id"] == policy
        ),
        key=lambda row: (row.get("attempt_id") or ""),
    )
    if not candidates:
        return None
    return bool(candidates[0]["verified_success"])


def policy_disagreement(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Paired (same ``task_id``, two policies) 2x2 outcome analysis."""
    policy_a, policy_b = pair_policies(rows)
    task_ids = sorted({row["task_id"] for row in rows})
    total_tasks = len(task_ids)
    paired_tasks = 0
    unpaired_tasks = 0
    matrix = {"both_ok": 0, "a_only": 0, "b_only": 0, "both_fail": 0}
    by_family_counts: dict[str, dict[str, Any]] = {}
    for task_id in task_ids:
        present = {row["policy_id"] for row in rows if row["task_id"] == task_id}
        family = next(
            (row["family"] for row in rows if row["task_id"] == task_id),
            None,
        )
        if policy_a in present and policy_b in present:
            paired_tasks += 1
        else:
            unpaired_tasks += 1
            continue
        cell = by_family_counts.setdefault(
            family, {"paired": 0, "both_ok": 0, "a_only": 0, "b_only": 0, "both_fail": 0}
        )
        cell["paired"] += 1
        outcome_a = _task_policy_outcome(rows, task_id, policy_a)
        outcome_b = _task_policy_outcome(rows, task_id, policy_b)
        if outcome_a is None or outcome_b is None:
            continue
        if outcome_a and outcome_b:
            matrix["both_ok"] += 1
            cell["both_ok"] += 1
        elif outcome_a and not outcome_b:
            matrix["a_only"] += 1
            cell["a_only"] += 1
        elif not outcome_a and outcome_b:
            matrix["b_only"] += 1
            cell["b_only"] += 1
        else:
            matrix["both_fail"] += 1
            cell["both_fail"] += 1
    disagreement = matrix["a_only"] + matrix["b_only"]
    by_family: list[dict[str, Any]] = []
    for family in sorted(by_family_counts):
        cell = by_family_counts[family]
        cell = dict(cell)
        cell["family"] = family
        cell["disagreement"] = cell["a_only"] + cell["b_only"]
        cell["disagreement_rate"] = (
            cell["disagreement"] / cell["paired"] if cell["paired"] else None
        )
        by_family.append(cell)
    return {
        "policy_a": policy_a,
        "policy_b": policy_b,
        "matrix": matrix,
        "disagreement_count": disagreement,
        "disagreement_rate": disagreement / paired_tasks if paired_tasks else None,
        "paired_tasks": paired_tasks,
        "unpaired_tasks": unpaired_tasks,
        "total_tasks": total_tasks,
        "by_family": by_family,
    }


def failure_analysis(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Failure counts and rates by task family and by failure code."""
    total_rows = len(rows)
    failures = [row for row in rows if not row["verified_success"]]
    failure_count = len(failures)
    by_family: dict[str, dict[str, int]] = {}
    by_code: Counter[str] = Counter()
    for row in rows:
        family = row["family"]
        cell = by_family.setdefault(family, {"total": 0, "failures": 0})
        cell["total"] += 1
        if not row["verified_success"]:
            cell["failures"] += 1
            if row.get("failure_code") is not None:
                by_code[row["failure_code"]] += 1
    family_rows: list[dict[str, Any]] = []
    for family in sorted(by_family):
        cell = by_family[family]
        family_rows.append(
            {
                "family": family,
                "total": cell["total"],
                "failures": cell["failures"],
                "failure_rate": (
                    cell["failures"] / cell["total"] if cell["total"] else None
                ),
            }
        )
    code_rows: list[dict[str, Any]] = []
    for code, count in sorted(by_code.items(), key=lambda item: (-item[1], item[0])):
        code_rows.append(
            {
                "code": code,
                "count": count,
                "share_of_failures": (
                    count / failure_count if failure_count else None
                ),
                "failure_rate": count / total_rows if total_rows else None,
            }
        )
    return {
        "total_rows": total_rows,
        "failure_count": failure_count,
        "failure_rate": failure_count / total_rows if total_rows else None,
        "by_family": family_rows,
        "by_code": code_rows,
    }


def cost_stats(rows: list[dict[str, Any]]) -> dict[str, Any]:
    """Mean/std/min/max of tokens, tool calls and messages by family x policy."""
    groups: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in rows:
        groups.setdefault((row["family"], row["policy_id"]), []).append(row)
    out_rows: list[dict[str, Any]] = []
    for key in sorted(groups):
        family, policy = key
        members = groups[key]
        tokens = [float(total_tokens(row)) for row in members]
        tools = [float(row.get("tool_call_count") or 0) for row in members]
        messages = [float(row.get("assistant_message_count") or 0) for row in members]

        def _bundle(values: list[float]) -> dict[str, float | None]:
            lo, hi = _min_max(values)
            return {
                "mean": _mean(values),
                "std": _pop_std(values),
                "min": lo,
                "max": hi,
            }

        out_rows.append(
            {
                "family": family,
                "policy": policy,
                "n": len(members),
                "total_tokens": _bundle(tokens),
                "tool_calls": _bundle(tools),
                "assistant_messages": _bundle(messages),
            }
        )
    return {"rows": out_rows}


# ---------------------------------------------------------------------------
# Optional input parsers (metrics.json, baselines JSON)
# ---------------------------------------------------------------------------
def _parse_metrics(metrics_path: str | Path | None) -> dict[str, Any]:
    """Parse the optional outcome-model ``metrics.json`` into a safe bundle.

    Returns ``{"status": "present"|"missing"|"malformed", "warning", ...}``.
    Only whitelisted aggregate metric keys are kept; unknown keys (e.g. raw
    posterior samples) are dropped.  Binned calibration data is kept only when
    actually present in the file.
    """
    result: dict[str, Any] = {
        "status": "missing",
        "warning": None,
        "splits": [],
        "per_policy": [],
        "calibration": [],
        "has_calibration": False,
    }
    if metrics_path is None:
        return result
    path = Path(metrics_path).expanduser().resolve()
    if not path.is_file():
        result["warning"] = f"metrics file not found: {path}"
        return result
    try:
        with path.open("r", encoding="utf-8") as handle:
            raw = json.load(handle)
    except (json.JSONDecodeError, OSError) as error:
        result["status"] = "malformed"
        result["warning"] = f"metrics file unreadable: {error}"
        return result
    if not isinstance(raw, dict):
        result["status"] = "malformed"
        result["warning"] = "metrics JSON is not an object"
        return result

    split_names = [name for name in _SPLIT_ORDER if name in raw]
    split_names += sorted(name for name in raw if name not in _SPLIT_ORDER)
    split_names = [
        name
        for name in split_names
        if name != "calibration" and isinstance(raw.get(name), dict)
    ]
    if not split_names:
        result["status"] = "malformed"
        result["warning"] = "metrics JSON has no recognized split bundles"
        return result

    per_policy: list[dict[str, Any]] = []
    splits: list[dict[str, Any]] = []
    for name in split_names:
        bundle = raw[name]
        split_entry: dict[str, Any] = {"split": name}
        for key in ("n", *_MODEL_METRIC_KEYS):
            value = _finite_float(bundle.get(key))
            if key == "n":
                split_entry[key] = int(value) if value is not None else 0
            else:
                split_entry[key] = value
        splits.append(split_entry)
        policies = bundle.get("per_policy")
        if isinstance(policies, dict):
            for policy_id in sorted(policies):
                sub = policies[policy_id]
                if not isinstance(sub, dict):
                    continue
                entry: dict[str, Any] = {"split": name, "policy": policy_id}
                for key in ("n", *_MODEL_METRIC_KEYS):
                    value = _finite_float(sub.get(key))
                    if key == "n":
                        entry[key] = int(value) if value is not None else 0
                    else:
                        entry[key] = value
                per_policy.append(entry)

    result["splits"] = splits
    result["per_policy"] = per_policy
    result["calibration"] = _parse_calibration(raw.get("calibration"))
    result["has_calibration"] = any(bins["bins"] for bins in result["calibration"])
    result["status"] = "present"
    return result


def _parse_calibration(value: Any) -> list[dict[str, Any]]:
    """Normalize optional binned calibration data, or return ``[]``.

    Accepted shapes (only when real binned data exists):
    * ``{"train": [bin, ...], ...}`` keyed by split
    * ``[bin, ...]`` global bins
    * ``[{"split": "...", "confidence": .., "accuracy": .., "count": ..}, ...]``
    Each bin needs finite ``confidence``/``accuracy`` in ``[0, 1]`` and a
    non-negative integer ``count``; anything else is dropped, so aggregate
    metrics can never be fabricated into a calibration curve.
    """
    if value is None:
        return []

    def _clean_bin(bin_value: Any) -> dict[str, Any] | None:
        if not isinstance(bin_value, dict):
            return None
        confidence = _finite_float(bin_value.get("confidence"))
        accuracy = _finite_float(bin_value.get("accuracy"))
        count = _i(bin_value.get("count"))
        if confidence is None or accuracy is None:
            return None
        if not (0.0 <= confidence <= 1.0 and 0.0 <= accuracy <= 1.0):
            return None
        return {
            "lower": _finite_float(bin_value.get("lower")),
            "upper": _finite_float(bin_value.get("upper")),
            "confidence": confidence,
            "accuracy": accuracy,
            "count": max(count, 0),
        }

    result: list[dict[str, Any]] = []
    if isinstance(value, dict):
        for split in sorted(value):
            bins_value = value[split]
            if isinstance(bins_value, list):
                bins = [b for b in (_clean_bin(b) for b in bins_value) if b is not None]
                if bins:
                    result.append({"split": split, "bins": bins})
    elif isinstance(value, list):
        grouped: dict[str, list[dict[str, Any]]] = {}
        global_bins: list[dict[str, Any]] = []
        for bin_value in value:
            cleaned = _clean_bin(bin_value)
            if cleaned is None:
                continue
            split = bin_value.get("split")
            if isinstance(split, str) and split:
                grouped.setdefault(split, []).append(cleaned)
            else:
                global_bins.append(cleaned)
        for split in sorted(grouped):
            result.append({"split": split, "bins": grouped[split]})
        if global_bins:
            result.append({"split": "all", "bins": global_bins})
    return result


def _baseline_number(bundle: dict[str, Any], aliases: Iterable[str]) -> float | None:
    for key in aliases:
        value = _finite_float(bundle.get(key))
        if value is not None:
            return value
    return None


def _parse_baselines(baselines_path: str | Path | None) -> dict[str, Any]:
    """Parse the optional allocator baseline JSON into a safe strategy table."""
    result: dict[str, Any] = {
        "status": "missing",
        "warning": None,
        "rows": [],
    }
    if baselines_path is None:
        return result
    path = Path(baselines_path).expanduser().resolve()
    if not path.is_file():
        result["warning"] = f"baselines file not found: {path}"
        return result
    try:
        with path.open("r", encoding="utf-8") as handle:
            raw = json.load(handle)
    except (json.JSONDecodeError, OSError) as error:
        result["status"] = "malformed"
        result["warning"] = f"baselines file unreadable: {error}"
        return result

    entries: list[tuple[str, dict[str, Any]]] = []
    if isinstance(raw, dict) and "strategies" in raw and isinstance(raw["strategies"], (dict, list)):
        raw = raw["strategies"]
    if isinstance(raw, dict):
        for name in sorted(raw):
            bundle = raw[name]
            if isinstance(bundle, dict):
                entries.append((str(name), bundle))
    elif isinstance(raw, list):
        for item in raw:
            if isinstance(item, dict):
                name = item.get("strategy") or item.get("name")
                if isinstance(name, str) and name:
                    entries.append((name, item))
    if not entries:
        result["status"] = "malformed"
        result["warning"] = "baselines JSON contains no usable strategy rows"
        return result

    rows: list[dict[str, Any]] = []
    for name, bundle in entries:
        success = _baseline_number(bundle, _BASELINE_SUCCESS_ALIASES)
        if success is not None and success > 1.0:
            # Accept percentage-style values (73.2 -> 0.732).
            success = success / 100.0
        n_value = _baseline_number(bundle, _BASELINE_N_ALIASES)
        rows.append(
            {
                "strategy": name,
                "success_rate": success,
                "n": int(n_value) if n_value is not None else None,
                "mean_tokens": _baseline_number(bundle, _BASELINE_TOKENS_ALIASES),
                "mean_tool_calls": _baseline_number(bundle, _BASELINE_TOOLS_ALIASES),
                "mean_messages": _baseline_number(bundle, _BASELINE_MSGS_ALIASES),
            }
        )
    result["status"] = "present"
    result["rows"] = rows
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def build_dashboard_data(
    dataset_path: str | Path,
    metrics_path: str | Path | None = None,
    baselines_path: str | Path | None = None,
    *,
    title: str | None = None,
) -> dict[str, Any]:
    """Assemble every piece of dashboard data from the three input sources.

    The returned dict is JSON-serializable and self-contained: it carries the
    sanitized public rows (all of them, so the browser-side filters can
    recompute every section), the precomputed *unfiltered* aggregates used for
    the static markup, and the normalized optional inputs.
    """
    dataset = Path(dataset_path).expanduser().resolve()
    rows, skipped = _load_dataset_rows(dataset)
    public_rows = [_row_to_public(row) for row in rows]
    public_rows.sort(key=lambda row: (row["task_id"] or "", row["policy_id"] or "", row["attempt_id"] or ""))

    warnings: list[str] = []
    if skipped:
        warnings.append(f"{skipped} dataset row(s) skipped: missing identity or label keys")
    model = _parse_metrics(metrics_path)
    baselines = _parse_baselines(baselines_path)
    if model["warning"]:
        warnings.append(model["warning"])
    if baselines["warning"]:
        warnings.append(baselines["warning"])

    filters = {
        "family": sorted({row["family"] for row in public_rows}),
        "difficulty": sorted({row["difficulty"] for row in public_rows}),
        "policy": sorted({row["policy_id"] for row in public_rows}),
    }
    meta = {
        "title": title or "Pyreplab Harness Dashboard",
        # Only file basenames are embedded; absolute paths (which can carry a
        # username or host layout) never reach the HTML or the DATA payload.
        "dataset_basename": dataset.name,
        "metrics_basename": Path(metrics_path).expanduser().resolve().name if metrics_path else None,
        "baselines_basename": Path(baselines_path).expanduser().resolve().name if baselines_path else None,
        "rows": len(public_rows),
        "model_status": model["status"],
        "baselines_status": baselines["status"],
        "warnings": warnings,
    }
    return {
        "meta": meta,
        "filters": filters,
        "rows": public_rows,
        "gym": aggregate_gym(public_rows),
        "disagreement": policy_disagreement(public_rows),
        "failures": failure_analysis(public_rows),
        "costs": cost_stats(public_rows),
        "model": model,
        "baselines": baselines,
        "config": {
            "browser_cap": BROWSER_ROW_CAP,
            "prompt_preview_limit": PROMPT_PREVIEW_LIMIT,
        },
    }


# ---------------------------------------------------------------------------
# Static HTML rendering (unfiltered state; testable without JavaScript)
# ---------------------------------------------------------------------------
def _policy_color(policy: str | None) -> str:
    if policy is None:
        return "#607D8B"
    if policy in _POLICY_COLORS:
        return _POLICY_COLORS[policy]
    return _PALETTE[hash_sort_key(policy) % len(_PALETTE)]


def hash_sort_key(value: str) -> int:
    """Deterministic stable hash used only for palette selection."""
    return sum((ord(char) * (index + 1)) for index, char in enumerate(value))


def _bar(value: float | None, color: str) -> str:
    if value is None:
        return ""
    width = max(0.0, min(100.0, value * 100.0))
    return (
        f'<div class="bar" aria-hidden="true">'
        f'<div class="bar-fill" style="width:{width:.1f}%;background-color:{color}"></div>'
        f"</div>"
    )


def _render_header(meta: dict[str, Any]) -> str:
    badges = []
    model_status = meta.get("model_status")
    if model_status == "present":
        badges.append('<span class="badge b-ok">✓ Model metrics: available</span>')
    elif model_status == "malformed":
        badges.append('<span class="badge b-bad">✗ Model metrics: unreadable</span>')
    else:
        badges.append('<span class="badge b-muted">— Model metrics: not provided</span>')
    baseline_status = meta.get("baselines_status")
    if baseline_status == "present":
        badges.append('<span class="badge b-ok">✓ Allocator baselines: available</span>')
    elif baseline_status == "malformed":
        badges.append('<span class="badge b-bad">✗ Allocator baselines: unreadable</span>')
    else:
        badges.append('<span class="badge b-muted">— Allocator baselines: not provided</span>')

    source_rows = []
    if meta.get("dataset_basename"):
        source_rows.append(
            f"<li><span>Dataset:</span> <code>{_esc(meta['dataset_basename'])}</code></li>"
        )
    if meta.get("metrics_basename"):
        source_rows.append(
            f"<li><span>Outcome model metrics:</span> <code>{_esc(meta['metrics_basename'])}</code></li>"
        )
    if meta.get("baselines_basename"):
        source_rows.append(
            f"<li><span>Allocator baselines:</span> <code>{_esc(meta['baselines_basename'])}</code></li>"
        )
    warnings = "".join(
        f"<li>{_esc(warning)}</li>" for warning in meta.get("warnings") or []
    )
    return f"""
<header class="top">
  <div class="wrap">
    <div class="header-grid">
      <div>
        <h1>{_esc(meta.get('title', 'Pyreplab Harness Dashboard'))}</h1>
        <p class="subtitle">Verified-attempt research workbench · {_esc(meta.get('rows', 0))} attempts</p>
        <p class="badges">{''.join(badges)}</p>
      </div>
      <div class="export-meta">
        <h2 class="visually-hidden" id="heading-export">Export metadata</h2>
        <ul class="meta-list">
          {''.join(source_rows)}
        </ul>
        <details>
          <summary>Warnings ({len(meta.get('warnings') or [])})</summary>
          <ul>{warnings}</ul>
        </details>
      </div>
    </div>
  </div>
</header>"""


def _render_filters(filters: dict[str, list[str]]) -> str:
    def _group(dim: str, label: str) -> str:
        options = filters.get(dim) or []
        controls = "".join(
            (
                f'<label class="chip"><input type="checkbox" data-filter="{dim}" '
                f'value="{_esc(value)}" checked> {_esc(value or "—")}</label>'
            )
            for value in options
        )
        if not controls:
            controls = '<span class="muted">none present</span>'
        return (
            f'<fieldset><legend>{label}</legend><div class="chip-row">{controls}</div></fieldset>'
        )

    return f"""
<form id="filters" aria-label="Dashboard filters" class="card">
  <div class="filter-head">
    <h2 id="heading-filters">Filters</h2>
    <button type="button" id="filter-reset" class="btn">Reset</button>
  </div>
  <div class="filter-groups">
    {_group("family", "Family")}
    {_group("difficulty", "Difficulty")}
    {_group("policy", "Policy")}
  </div>
  <p id="filter-count" aria-live="polite" class="muted">—</p>
</form>"""


def _render_gym(gym: dict[str, Any]) -> str:
    def _kpi(label: str, value: str, note: str, cue: str = "") -> str:
        return (
            f'<div class="kpi"><span class="kpi-label">{_esc(label)}</span>'
            f'<span class="kpi-value">{_esc(value)}</span>'
            f'<span class="kpi-note">{_esc(note)} {_esc(cue)}</span></div>'
        )

    success = gym.get("overall_success_rate")
    success_cue = "✓" if success is not None and success >= 0.5 else "✗"
    coverage = gym.get("task_coverage")
    disagreement = gym.get("disagreement_rate")
    kpis = (
        _kpi("Overall success", _fmt_pct(success), "of attempts", success_cue)
        + _kpi("Task coverage", _fmt_pct(coverage), "tasks with both policies", "")
        + _kpi("Paired disagreement", _fmt_pct(disagreement), "of paired tasks", "")
        + _kpi("Avg total tokens", _fmt_num(gym.get("avg_total_tokens"), 0), "per attempt", "")
    )

    header = (
        "<tr>"
        "<th scope=\"col\">Family</th><th scope=\"col\">Policy</th>"
        "<th scope=\"col\">Attempts</th><th scope=\"col\">Success</th>"
        "<th scope=\"col\">Success rate</th><th scope=\"col\">Distribution</th>"
        "</tr>"
    )
    body_parts = []
    for cell in gym.get("family_policy") or []:
        rate = cell.get("success_rate")
        cue = "✓" if rate is not None and rate >= 0.5 else "✗"
        color = _policy_color(cell.get("policy"))
        body_parts.append(
            f'<tr><td>{_esc(cell.get("family"))}</td>'
            f'<td><span class="dot" style="background-color:{color}"></span> {_esc(cell.get("policy"))}</td>'
            f'<td>{cell.get("n")}</td><td>{cell.get("success")}</td>'
            f'<td>{_fmt_pct(rate)} {cue}</td>'
            f'<td class="cell-bar">{_bar(rate, color)}{_fmt_pct(rate)}</td></tr>'
        )
    if not body_parts:
        body_parts = ['<tr><td colspan="6" class="empty">No verified attempts to aggregate.</td></tr>']
    return f"""
<div class="kpis">{kpis}</div>
<div class="card">
  <h3>Success by family × policy</h3>
  <div class="table-scroll"><table class="data">
    <caption class="visually-hidden">Verified success rate by task family and policy</caption>
    <thead>{header}</thead>
    <tbody>{''.join(body_parts)}</tbody>
  </table></div>
</div>"""


def _cell_class(color: str) -> str:
    """Outcome-matrix cell tint for a policy accent color."""
    if color == "#1565C0":
        return "cell-a"
    if color == "#E65100":
        return "cell-b"
    return "cell-neutral"


def _render_disagreement(dis: dict[str, Any]) -> str:
    a = dis.get("policy_a")
    b = dis.get("policy_b")
    matrix = dis.get("matrix") or {}
    a_color = _policy_color(a)
    b_color = _policy_color(b)
    a_cls = _cell_class(a_color)
    b_cls = _cell_class(b_color)
    win_text = (
        f'<p class="muted">Compared policies: '
        f'<span class="dot" style="background-color:{a_color}"></span> '
        f'{_esc(a or "—")} vs <span class="dot" style="background-color:{b_color}"></span> '
        f'{_esc(b or "—")}. '
        f'{_esc(a or "—")}-only wins: <strong>{matrix.get("a_only", 0)}</strong> · '
        f'{_esc(b or "—")}-only wins: <strong>{matrix.get("b_only", 0)}</strong>.</p>'
    )
    if dis.get("paired_tasks", 0) == 0:
        return f"""
<div class="state-note" role="status">No paired tasks to compare — the dataset needs at least two policies run on the same task.</div>
{win_text}"""

    cells = [
        ("both_ok", "Both succeed", f'{matrix.get("both_ok", 0)}', "cell-ok"),
        ("a_only", f'{_esc(a)} succeeds only', f'{matrix.get("a_only", 0)}', a_cls),
        ("b_only", f'{_esc(b)} succeeds only', f'{matrix.get("b_only", 0)}', b_cls),
        ("both_fail", "Both fail", f'{matrix.get("both_fail", 0)}', "cell-bad"),
    ]
    cell_html = "".join(
        f'<tr><td class="label">{_esc(label)}</td><td class="num {cls}">{count}</td></tr>'
        for _key, label, count, cls in cells
    )
    family_headers = (
        "<tr>"
        f'<th scope="col">Family</th><th scope="col">Paired tasks</th>'
        f'<th scope="col">Both ✓</th><th scope="col">{_esc(a)} only ✓</th>'
        f'<th scope="col">{_esc(b)} only ✓</th><th scope="col">Both ✗</th>'
        '<th scope="col">Disagreement</th><th scope="col">Disagreement rate</th>'
        "</tr>"
    )
    family_parts = []
    for row in dis.get("by_family") or []:
        family_parts.append(
            f'<tr><td>{_esc(row.get("family"))}</td><td>{row.get("paired")}</td>'
            f'<td>{row.get("both_ok")}</td><td>{row.get("a_only")}</td>'
            f'<td>{row.get("b_only")}</td><td>{row.get("both_fail")}</td>'
            f'<td>{row.get("disagreement")}</td>'
            f'<td>{_fmt_pct(row.get("disagreement_rate"))}</td></tr>'
        )
    if not family_parts:
        family_parts = ['<tr><td colspan="8" class="empty">No paired families.</td></tr>']
    return f"""
{win_text}
<div class="card">
  <h3>2×2 paired outcome matrix</h3>
  <div class="matrix-grid">
    <table class="matrix">
      <caption class="visually-hidden">Paired outcome matrix for {_esc(a)} and {_esc(b)}</caption>
      <tbody>{cell_html}</tbody>
    </table>
    <p class="muted note">Paired by <code>task_id</code>: one representative attempt per policy (first by attempt id). A task counts once. <strong>{dis.get("paired_tasks")}</strong> paired task(s) out of {dis.get("total_tasks")}.</p>
  </div>
</div>
<div class="card">
  <h3>Disagreement by family</h3>
  <div class="table-scroll"><table class="data">
    <caption class="visually-hidden">Paired disagreement by task family</caption>
    <thead>{family_headers}</thead>
    <tbody>{''.join(family_parts)}</tbody>
  </table></div>
</div>"""


def _render_failures(failures: dict[str, Any]) -> str:
    family_headers = (
        "<tr><th scope=\"col\">Family</th><th scope=\"col\">Attempts</th>"
        "<th scope=\"col\">Failures</th><th scope=\"col\">Failure rate</th>"
        "<th scope=\"col\">Distribution</th></tr>"
    )
    family_parts = []
    for row in failures.get("by_family") or []:
        rate = row.get("failure_rate")
        family_parts.append(
            f'<tr><td>{_esc(row.get("family"))}</td><td>{row.get("total")}</td>'
            f'<td>{row.get("failures")}</td><td>{_fmt_pct(rate)}</td>'
            f'<td class="cell-bar">{_bar(rate, "#C62828")}{_fmt_pct(rate)}</td></tr>'
        )
    if not family_parts:
        family_parts = ['<tr><td colspan="5" class="empty">No attempts.</td></tr>']
    code_headers = (
        "<tr><th scope=\"col\">Failure code</th><th scope=\"col\">Count</th>"
        "<th scope=\"col\">Share of failures</th><th scope=\"col\">Failure rate</th></tr>"
    )
    code_parts = []
    for row in failures.get("by_code") or []:
        code_parts.append(
            f'<tr><td><code>{_esc(row.get("code"))}</code></td><td>{row.get("count")}</td>'
            f'<td>{_fmt_pct(row.get("share_of_failures"))}</td>'
            f'<td>{_fmt_pct(row.get("failure_rate"))}</td></tr>'
        )
    if not code_parts:
        code_parts = ['<tr><td colspan="4" class="empty">No verified failures recorded.</td></tr>']
    return f"""
<p class="muted">Overall failure rate: <strong>{_fmt_pct(failures.get("failure_rate"))}</strong> ({failures.get("failure_count")} of {failures.get("total_rows")} attempts).</p>
<div class="card">
  <h3>Failures by family</h3>
  <div class="table-scroll"><table class="data">
    <caption class="visually-hidden">Failure counts and rates by task family</caption>
    <thead>{family_headers}</thead><tbody>{''.join(family_parts)}</tbody>
  </table></div>
</div>
<div class="card">
  <h3>Failures by code</h3>
  <div class="table-scroll"><table class="data">
    <caption class="visually-hidden">Failure counts and rates by failure code</caption>
    <thead>{code_headers}</thead><tbody>{''.join(code_parts)}</tbody>
  </table></div>
</div>"""


def _render_cost_row(row: dict[str, Any]) -> str:
    n = row.get("n", 0)

    def _cells(bundle: dict[str, Any]) -> str:
        if n <= 1:
            # A single observation cannot back a std or a min-max range.
            return f'<td>{_fmt_num(bundle.get("mean"), 1)}</td><td>—</td>'
        return (
            f'<td>{_fmt_num(bundle.get("mean"), 1)} ± {_fmt_num(bundle.get("std"), 1)}</td>'
            f'<td>{_fmt_int(bundle.get("min"))}–{_fmt_int(bundle.get("max"))}</td>'
        )

    return (
        f'<tr><td>{_esc(row.get("family"))}</td>'
        f'<td><span class="dot" style="background-color:{_policy_color(row.get("policy"))}"></span> {_esc(row.get("policy"))}</td>'
        f'<td>{n}</td>'
        f'{_cells(row.get("total_tokens") or {})}'
        f'{_cells(row.get("tool_calls") or {})}'
        f'{_cells(row.get("assistant_messages") or {})}</tr>'
    )


def _render_costs(costs: dict[str, Any]) -> str:
    headers = (
        "<tr><th scope=\"col\">Family</th><th scope=\"col\">Policy</th><th scope=\"col\">n</th>"
        "<th scope=\"col\">Total tokens mean ± std</th><th scope=\"col\">Tokens min–max</th>"
        "<th scope=\"col\">Tool calls mean ± std</th><th scope=\"col\">Tools min–max</th>"
        "<th scope=\"col\">Messages mean ± std</th><th scope=\"col\">Messages min–max</th></tr>"
    )
    parts = [_render_cost_row(row) for row in costs.get("rows") or []]
    if not parts:
        parts = ['<tr><td colspan="9" class="empty">No cost data to aggregate.</td></tr>']
    return f"""
<div class="card">
  <h3>Cost comparison by family × policy</h3>
  <div class="table-scroll"><table class="data">
    <caption class="visually-hidden">Token, tool-call and message cost statistics by family and policy</caption>
    <thead>{headers}</thead><tbody>{''.join(parts)}</tbody>
  </table></div>
</div>"""


def _render_metric_table(rows: list[dict[str, Any]], key_headers: list[tuple[str, str]]) -> str:
    """Metric table with one or more identity columns first.

    ``key_headers`` is an ordered list of ``(field, header label)`` pairs; the
    static columns always match the columns the inline JavaScript renders for
    the same table (the per-policy table shows Policy then Split).
    """
    col_count = len(key_headers) + 6
    headers = (
        "<tr>"
        + "".join(f'<th scope="col">{_esc(label)}</th>' for _field, label in key_headers)
        + (
            '<th scope="col">n</th><th scope="col">Log loss</th><th scope="col">Brier</th>'
            '<th scope="col">Accuracy</th><th scope="col">ECE</th>'
            '<th scope="col">Posterior std</th></tr>'
        )
    )
    parts = []
    for row in rows:
        identity = "".join(
            f'<td>{_esc(row.get(field))}</td>' for field, _label in key_headers
        )
        parts.append(
            f'<tr>{identity}<td>{row.get("n", 0)}</td>'
            f'<td>{_fmt_num(row.get("log_loss"), 4)}</td>'
            f'<td>{_fmt_num(row.get("brier"), 4)}</td>'
            f'<td>{_fmt_pct(row.get("accuracy_05"))}</td>'
            f'<td>{_fmt_num(row.get("ece"), 4)}</td>'
            f'<td>{_fmt_num(row.get("mean_posterior_std"), 4)}</td></tr>'
        )
    if not parts:
        parts = [
            f'<tr><td colspan="{col_count}" class="empty">No rows.</td></tr>'
        ]
    return (
        '<div class="table-scroll"><table class="data">'
        f"<thead>{headers}</thead><tbody>{''.join(parts)}</tbody></table></div>"
    )


def _render_calibration_chart(calibration: list[dict[str, Any]]) -> str:
    """Reliability SVG only when real binned calibration data exists."""
    if not calibration:
        return '<p class="muted">No binned calibration data present — a calibration plot is not drawn (it cannot be fabricated from aggregate metrics).</p>'
    width, height = 640, 380
    left, right, top, bottom = 55, 20, 28, 42
    pw, ph = width - left - right, height - top - bottom
    parts: list[str] = []

    def _px(value: float) -> float:
        return left + value * pw

    def _py(value: float) -> float:
        return top + ph - value * ph

    parts.append(f'<line x1="{_px(0):.1f}" y1="{_py(0):.1f}" x2="{_px(1):.1f}" y2="{_py(1):.1f}" class="ref-line"/>')
    for index in range(6):
        value = index / 5
        y = _py(value)
        parts.append(f'<line x1="{left}" y1="{y:.1f}" x2="{width - right}" y2="{y:.1f}" class="grid"/>')
        parts.append(f'<text x="{left - 8}" y="{y + 4:.1f}" text-anchor="end" class="axis-label">{value:.1f}</text>')

    groups: list[str] = []
    for group in calibration:
        bins = group.get("bins") or []
        split = group.get("split", "all")
        inner: list[str] = []
        band = pw / max(len(bins), 1)
        bar_width = band * 0.35
        for index, bin_value in enumerate(bins):
            x = _px(index / max(len(bins), 1))
            conf_h = _py(bin_value["confidence"])
            acc_h = _py(bin_value["accuracy"])
            inner.append(
                f'<rect x="{x + bar_width * 0.15:.1f}" y="{conf_h:.1f}" width="{bar_width:.1f}" '
                f'height="{_py(0) - conf_h:.1f}" fill="#1565C0"/>'
            )
            inner.append(
                f'<rect x="{x + bar_width * 1.15:.1f}" y="{acc_h:.1f}" width="{bar_width:.1f}" '
                f'height="{_py(0) - acc_h:.1f}" fill="#E65100"/>'
            )
            inner.append(
                f'<text x="{x + band / 2:.1f}" y="{_py(0) + 16:.1f}" text-anchor="middle" class="axis-label">{index + 1}</text>'
            )
        bins_table = _render_bins_table(bins)
        groups.append(
            f'<div class="card"><h4>Calibration — split {_esc(split)}</h4>'
            f'<svg viewBox="0 0 {width} {height}" role="img" aria-label="Reliability diagram: mean confidence versus observed accuracy per bin for split {_esc(split)}" class="calibration-chart">'
            f'<title>Reliability diagram for split {_esc(split)}</title>'
            f'{"".join(parts)}{"".join(inner)}'
            f'</svg>{bins_table}</div>'
        )
    return f"""
<div class="calibration">
  <div class="legend"><span class="legend-swatch sw-blue"></span> confidence
    <span class="legend-swatch sw-orange"></span> accuracy
    <span class="legend-swatch sw-line"></span> ideal</div>
  {''.join(groups)}
</div>"""


def _render_bins_table(bins: list[dict[str, Any]]) -> str:
    headers = (
        "<tr><th scope=\"col\">Bin</th><th scope=\"col\">Range</th>"
        "<th scope=\"col\">Confidence</th><th scope=\"col\">Accuracy</th>"
        "<th scope=\"col\">Count</th></tr>"
    )
    parts = []
    for index, bin_value in enumerate(bins):
        low = bin_value.get("lower")
        high = bin_value.get("upper")
        if low is None and high is None:
            range_text = "—"
        else:
            range_text = f"[{_fmt_num(low, 3)} – {_fmt_num(high, 3)})"
        parts.append(
            f'<tr><td>{index + 1}</td><td>{range_text}</td>'
            f'<td>{_fmt_num(bin_value.get("confidence"), 3)}</td>'
            f'<td>{_fmt_num(bin_value.get("accuracy"), 3)}</td>'
            f'<td>{bin_value.get("count", 0)}</td></tr>'
        )
    return (
        '<div class="table-scroll"><table class="data">'
        f"<thead>{headers}</thead><tbody>{''.join(parts)}</tbody></table></div>"
    )


def _render_model(model: dict[str, Any]) -> str:
    if model.get("status") != "present":
        reason = model.get("warning") or "no metrics file was provided"
        return (
            f'<div class="state-note" role="status">'
            f'Model evaluation is not available ({_esc(reason)}). '
            f"Train and evaluate the outcome model to populate this section."
            f"</div>"
        )
    split_table = _render_metric_table(model.get("splits") or [], [("split", "Split")])
    policy_rows = model.get("per_policy") or []
    policy_table = _render_metric_table(
        policy_rows, [("policy", "Policy"), ("split", "Split")]
    )
    calibration = _render_calibration_chart(model.get("calibration") or [])
    return f"""
<div class="card">
  <h3>Metrics by split</h3>
  {split_table}
</div>
<div class="card">
  <h3>Metrics by policy (syncs with the policy filter)</h3>
  <div id="model-policy-wrap">{policy_table}</div>
</div>
<div class="card">
  <h3>Calibration</h3>
  {calibration}
</div>"""


def _render_baselines(baselines: dict[str, Any]) -> str:
    if baselines.get("status") != "present":
        reason = baselines.get("warning") or "no baselines file was provided"
        return (
            f'<div class="state-note" role="status">'
            f"Allocator baselines are not available ({_esc(reason)}). "
            f"Point the dashboard at an allocator baseline JSON to populate this section."
            f"</div>"
        )
    rows = baselines.get("rows") or []
    headers = (
        "<tr><th scope=\"col\">Strategy</th><th scope=\"col\">Verified success rate</th>"
        "<th scope=\"col\">n</th><th scope=\"col\">Mean tokens</th>"
        "<th scope=\"col\">Mean tool calls</th><th scope=\"col\">Mean messages</th></tr>"
    )
    parts = []
    for row in rows:
        rate = row.get("success_rate")
        parts.append(
            f'<tr><td>{_esc(row.get("strategy"))}</td>'
            f'<td>{_fmt_pct(rate)} {_bar(rate, _policy_color(row.get("strategy")))}</td>'
            f'<td>{row.get("n") if row.get("n") is not None else "—"}</td>'
            f'<td>{_fmt_num(row.get("mean_tokens"), 1)}</td>'
            f'<td>{_fmt_num(row.get("mean_tool_calls"), 1)}</td>'
            f'<td>{_fmt_num(row.get("mean_messages"), 1)}</td></tr>'
        )
    return f"""
<div class="card">
  <h3>Allocator baseline strategies</h3>
  <div class="table-scroll"><table class="data">
    <caption class="visually-hidden">Aggregate allocator baseline strategy results</caption>
    <thead>{headers}</thead><tbody>{''.join(parts)}</tbody>
  </table></div>
</div>"""


def _render_browser(rows: list[dict[str, Any]], cap: int) -> str:
    total = len(rows)
    shown = rows[:cap]
    headers = (
        "<tr>"
        "<th scope=\"col\">Task</th><th scope=\"col\">Family</th><th scope=\"col\">Difficulty</th>"
        "<th scope=\"col\">Policy</th><th scope=\"col\">Split</th><th scope=\"col\">Outcome</th>"
        "<th scope=\"col\">Failure code</th><th scope=\"col\">Verifier</th>"
        "<th scope=\"col\">Tokens</th><th scope=\"col\">Tools</th><th scope=\"col\">Messages</th>"
        "<th scope=\"col\"><span class=\"visually-hidden\">Details</span></th>"
        "</tr>"
    )
    parts: list[str] = []
    for index, row in enumerate(shown):
        success = row.get("verified_success")
        cue = "✓" if success else "✗"
        outcome_class = "cell-ok" if success else "cell-bad"
        parts.append(
            f'<tr>'
            f'<td><code>{_esc(row.get("task_id"))}</code></td>'
            f'<td>{_esc(row.get("family"))}</td>'
            f'<td>{_esc(row.get("difficulty") or "—")}</td>'
            f'<td>{_esc(row.get("policy_id"))}</td>'
            f'<td>{_esc(row.get("split") or "—")}</td>'
            f'<td><span class="{outcome_class}">{cue}</span> '
            f'{"success" if success else "fail"}</td>'
            f'<td>{_esc(row.get("failure_code")) or "—"}</td>'
            f'<td>{_esc(row.get("verifier_id")) or "—"}</td>'
            f'<td>{total_tokens(row)}</td>'
            f'<td>{row.get("tool_call_count", 0)}</td>'
            f'<td>{row.get("assistant_message_count", 0)}</td>'
            f'<td><button type="button" class="btn-link" data-detail-toggle '
            f'aria-expanded="false" aria-controls="detail-{index}">Details</button></td>'
            f"</tr>"
        )
        parts.append(_render_detail_row(row, index))
    if not parts:
        parts = ['<tr><td colspan="12" class="empty">No attempts match the current filters.</td></tr>']
    count_line = (
        f'<p id="browser-count" aria-live="polite" class="muted">'
        f"Showing {len(shown)} of {total} attempts (capped at {cap} rows).</p>"
    )
    return f"""
{count_line}
<div class="table-scroll"><table class="data" id="browser-table">
  <caption class="visually-hidden">Verified attempt browser</caption>
  <thead>{headers}</thead>
  <tbody id="browser-tbody">{''.join(parts)}</tbody>
</table></div>"""


def _render_detail_row(row: dict[str, Any], index: int) -> str:
    usage = row.get("usage") or {}
    usage_text = ", ".join(f"{_esc(key)}: {value}" for key, value in sorted(usage.items())) or "—"
    metadata = row.get("metadata") or {}
    metadata_text = (
        ", ".join(
            f"{_esc(key)}: {_esc(value)}"
            for key, value in sorted(metadata.items(), key=lambda item: str(item[0]))
        )
        or "—"
    )
    return (
        f'<tr class="detail-row hidden" id="detail-{index}">'
        f'<td colspan="12"><div class="detail-grid">'
        f'<div><strong>Prompt preview</strong><p>{_esc(row.get("prompt_preview")) or "—"}</p></div>'
        f'<dl class="detail-list">'
        f"<div><dt>Template</dt><dd>{_esc(row.get('template_id')) or '—'}</dd></div>"
        f"<div><dt>Generator version</dt><dd>{_esc(row.get('generator_version')) or '—'}</dd></div>"
        f"<div><dt>Seed</dt><dd>{row.get('seed', 0)}</dd></div>"
        f"<div><dt>Policy version</dt><dd>{_esc(row.get('policy_version')) or '—'}</dd></div>"
        f"<div><dt>Verifier version</dt><dd>{_esc(row.get('verifier_version')) or '—'}</dd></div>"
        f"<div><dt>Final text length</dt><dd>{row.get('final_text_length', 0)}</dd></div>"
        f'<div><dt>Usage</dt><dd>{usage_text}</dd></div>'
        f'<div><dt>Metadata</dt><dd>{metadata_text}</dd></div>'
        f"</dl></div></td></tr>"
    )


# ---------------------------------------------------------------------------
# HTML template assembly
# ---------------------------------------------------------------------------
def _render_banner(meta: dict[str, Any]) -> str:
    """Small-sample warning banner for datasets with fewer than 30 attempts."""
    rows = int(meta.get("rows") or 0)
    if 0 < rows < _SMALL_SAMPLE_THRESHOLD:
        return (
            f'<p class="banner" role="status">⚠ Small sample — only {rows} verified '
            f"attempts; aggregate statistics may be unstable.</p>"
        )
    return ""


def render_dashboard(data: dict[str, Any]) -> str:
    """Render ``data`` (from :func:`build_dashboard_data`) into a standalone HTML string."""
    meta = data.get("meta") or {}
    gym = data.get("gym") or {}
    disagreement = data.get("disagreement") or {}
    failures = data.get("failures") or {}
    costs = data.get("costs") or {}
    model = data.get("model") or {}
    baselines = data.get("baselines") or {}
    filters = data.get("filters") or {}
    config = data.get("config") or {}
    cap = int(config.get("browser_cap", BROWSER_ROW_CAP))

    header = _render_header(meta)
    banner = _render_banner(meta)
    filter_bar = _render_filters(filters)
    gym_html = _render_gym(gym)
    disagreement_html = _render_disagreement(disagreement)
    failures_html = _render_failures(failures)
    costs_html = _render_costs(costs)
    model_html = _render_model(model)
    baselines_html = _render_baselines(baselines)
    browser_html = _render_browser(data.get("rows") or [], cap)
    payload = _json_script_safe(data)

    return _TEMPLATE.replace("__HEADER__", header).replace(
        "__BANNER__", banner
    ).replace("__FILTERS__", filter_bar).replace("__GYM__", gym_html).replace(
        "__DISAGREEMENT__", disagreement_html
    ).replace("__FAILURES__", failures_html).replace(
        "__COSTS__", costs_html
    ).replace("__MODEL__", model_html).replace(
        "__BASELINES__", baselines_html
    ).replace("__BROWSER__", browser_html).replace(
        "__DATA_JSON__", payload
    )


def write_dashboard(
    dataset_path: str | Path,
    output_path: str | Path,
    metrics_path: str | Path | None = None,
    baselines_path: str | Path | None = None,
    *,
    title: str | None = None,
) -> dict[str, Any]:
    """Build and atomically write the standalone dashboard HTML.

    Returns a summary dict with the output path, byte size, row counts and
    model/baseline statuses.  The write is atomic (same-directory temp file +
    ``os.replace``), so a failed write never leaves a partial dashboard.
    """
    data = build_dashboard_data(dataset_path, metrics_path, baselines_path, title=title)
    html_doc = render_dashboard(data)
    target = Path(output_path).expanduser().resolve()
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        dir=target.parent,
        prefix=f".{target.name}.",
        delete=False,
    ) as handle:
        handle.write(html_doc)
        temporary = Path(handle.name)
    os.replace(temporary, target)
    return {
        "output_path": str(target),
        "bytes": len(html_doc.encode("utf-8")),
        "rows": data["meta"]["rows"],
        "model_status": data["meta"]["model_status"],
        "baselines_status": data["meta"]["baselines_status"],
        "warnings": data["meta"]["warnings"],
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="pyreplab-harness-dashboard",
        description=(
            "Render a standalone static HTML dashboard for a pyreplab run "
            "(leakage-safe dataset + optional outcome-model metrics + optional "
            "allocator baselines)."
        ),
    )
    parser.add_argument("dataset", help="leakage-safe deterministic JSONL dataset")
    parser.add_argument("output", help="output standalone HTML path")
    parser.add_argument("--metrics", help="optional outcome-model metrics.json")
    parser.add_argument("--baselines", help="optional allocator baseline JSON")
    parser.add_argument("--title", help="dashboard title")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        summary = write_dashboard(
            args.dataset,
            args.output,
            metrics_path=args.metrics,
            baselines_path=args.baselines,
            title=args.title,
        )
    except (FileNotFoundError, ValueError, OSError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    print(json.dumps(summary, indent=2, sort_keys=True, ensure_ascii=False))
    return 0


__all__ = [
    "BROWSER_ROW_CAP",
    "PROMPT_PREVIEW_LIMIT",
    "aggregate_gym",
    "build_dashboard_data",
    "build_parser",
    "cost_stats",
    "failure_analysis",
    "main",
    "pair_policies",
    "policy_disagreement",
    "render_dashboard",
    "total_tokens",
    "write_dashboard",
]


# ===========================================================================
# HTML template with inline CSS and JavaScript (assembled via placeholders)
# ===========================================================================
_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Pyreplab Harness Dashboard</title>
<style>
  :root{
    --bg:#f4f5f7; --card:#ffffff; --border:#e3e6ea;
    --text:#1c2230; --muted:#5a6474;
    --blue:#1565C0; --orange:#E65100; --green:#2E7D32; --red:#C62828;
    --blue-soft:#E3F0FB; --orange-soft:#FDEDE1; --green-soft:#E8F5E9; --red-soft:#FDECEA;
    --focus:#1565C0; --radius:10px;
    --font:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  }
  *{box-sizing:border-box;}
  body{margin:0;background:var(--bg);color:var(--text);font-family:var(--font);line-height:1.5;font-size:16px;}
  .skip-link{position:absolute;left:-9999px;top:-9999px;width:1px;height:1px;overflow:hidden;}
  .skip-link:focus{position:fixed;left:8px;top:8px;width:auto;height:auto;overflow:visible;background:#fff;color:var(--text);padding:10px 14px;border-radius:6px;box-shadow:0 2px 10px rgba(0,0,0,.3);z-index:1000;font-weight:600;}
  .wrap{max-width:1280px;margin:0 auto;padding:0 20px 48px;}
  header.top{background:var(--card);border-bottom:1px solid var(--border);padding:20px 0 0;}
  .header-grid{display:flex;flex-wrap:wrap;gap:16px;justify-content:space-between;align-items:flex-start;}
  h1{font-size:26px;margin:0 0 4px;}
  h2{font-size:19px;margin:0 0 10px;}
  h3{font-size:18px;margin:0 0 10px;}
  h4{font-size:16px;margin:0 0 8px;}
  .subtitle{color:var(--muted);margin:0 0 10px;}
  .badges{display:flex;flex-wrap:wrap;gap:8px;}
  .badge{display:inline-block;padding:3px 10px;border-radius:999px;font-size:12.5px;font-weight:600;border:1px solid var(--border);}
  .b-ok{background:var(--green-soft);color:#1B5E20;border-color:#A5D6A7;}
  .b-bad{background:var(--red-soft);color:#B71C1C;border-color:#EF9A9A;}
  .b-muted{background:#EEF0F3;color:var(--muted);}
  .export-meta{max-width:460px;}
  .meta-list{list-style:none;margin:0 0 8px;padding:0;font-size:13px;color:var(--muted);}
  .meta-list code{font-size:12px;}
  .visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap;border:0;}
  nav ul.jump-links{list-style:none;display:flex;flex-wrap:wrap;gap:6px 18px;margin:14px 0 0;padding:0;}
  nav ul.jump-links a{color:var(--blue);font-size:13.5px;}
  section{margin-top:28px;}
  main{padding-top:8px;}
  .card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:16px 18px;margin-top:16px;}
  .muted{color:var(--muted);}
  .state-note{background:#EEF0F3;border:1px solid var(--border);border-radius:var(--radius);padding:14px 16px;color:var(--muted);margin-top:16px;}
  .banner{background:#FFF4E5;border:1px solid #F5C77E;color:#7A4E00;border-radius:var(--radius);padding:10px 14px;margin-top:16px;font-size:15px;}
  .empty{text-align:center;color:var(--muted);padding:18px 8px;}
  /* filter bar */
  #filters{margin-top:20px;}
  .filter-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px;}
  .filter-groups{display:flex;flex-wrap:wrap;gap:18px;}
  fieldset{border:1px solid var(--border);border-radius:8px;padding:8px 12px 10px;margin:0;min-width:180px;}
  legend{font-size:13px;font-weight:600;color:var(--muted);padding:0 4px;}
  .chip-row{display:flex;flex-wrap:wrap;gap:6px;}
  .chip{display:inline-flex;align-items:center;gap:5px;font-size:13.5px;padding:3px 9px;border:1px solid var(--border);border-radius:999px;background:#fff;cursor:pointer;}
  .chip:focus-within{outline:3px solid var(--focus);outline-offset:2px;}
  .btn{background:#fff;border:1px solid var(--border);border-radius:6px;padding:6px 14px;font:inherit;font-size:13.5px;cursor:pointer;color:var(--text);}
  .btn:hover{background:#f2f3f5;}
  .btn-link{background:none;border:none;color:var(--blue);text-decoration:underline;font:inherit;font-size:13px;cursor:pointer;padding:2px 4px;}
  /* KPI cards */
  .kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin-top:16px;}
  .kpi{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:14px 16px;display:flex;flex-direction:column;gap:2px;}
  .kpi-label{font-size:12.5px;color:var(--muted);}
  .kpi-value{font-size:24px;font-weight:650;}
  .kpi-note{font-size:12.5px;color:var(--muted);}
  /* tables */
  .table-scroll{overflow-x:auto;}
  table.data{border-collapse:collapse;width:100%;font-size:14px;}
  table.data th,table.data td{border:1px solid var(--border);padding:7px 10px;text-align:left;vertical-align:top;}
  table.data thead th{background:#f0f2f5;font-weight:600;}
  table.data tbody tr:nth-child(even){background:#fafbfc;}
  th[scope]{white-space:nowrap;}
  code{background:#eef0f3;border-radius:4px;padding:1px 4px;font-size:12.5px;}
  /* bars */
  .bar{display:inline-block;width:120px;height:12px;background:#e9ecf1;border-radius:6px;overflow:hidden;vertical-align:middle;}
  .bar-fill{height:100%;border-radius:6px;}
  .cell-bar{white-space:nowrap;}
  /* outcome cells */
  .cell-ok{background:var(--green-soft);color:#1B5E20;font-weight:600;}
  .cell-bad{background:var(--red-soft);color:#B71C1C;font-weight:600;}
  .cell-a{background:var(--blue-soft);color:#0D47A1;font-weight:600;}
  .cell-b{background:var(--orange-soft);color:#BF360C;font-weight:600;}
  .cell-neutral{background:#EEF0F3;color:var(--muted);font-weight:600;}
  .dot{display:inline-block;width:10px;height:10px;border-radius:50%;vertical-align:middle;}
  /* disagreement matrix */
  .matrix-grid{display:flex;flex-wrap:wrap;gap:20px;align-items:flex-start;}
  table.matrix{border-collapse:collapse;}
  table.matrix td{border:1px solid var(--border);padding:12px 18px;min-width:150px;font-size:14px;}
  table.matrix td.label{color:var(--muted);}
  table.matrix td.num{font-size:22px;font-weight:650;text-align:center;border-radius:8px;}
  .note{max-width:420px;}
  /* calibration */
  .calibration-chart{width:100%;max-width:640px;height:auto;border:1px solid var(--border);border-radius:8px;background:#fff;}
  .calibration-chart .grid{stroke:#e3e6ea;stroke-width:1;}
  .calibration-chart .ref-line{stroke:#90A4AE;stroke-width:1.5;stroke-dasharray:5 4;}
  .calibration-chart .axis-label{fill:#5a6474;font-size:11px;}
  .legend{font-size:12.5px;color:var(--muted);margin:6px 0 10px;}
  .legend-swatch{display:inline-block;width:12px;height:12px;border-radius:3px;vertical-align:-1px;margin-right:4px;}
  .sw-blue{background:#1565C0;}
  .sw-orange{background:#E65100;}
  .sw-line{background:repeating-linear-gradient(90deg,#90A4AE 0 3px,transparent 3px 6px);}
  /* attempt browser details */
  .detail-row.hidden{display:none;}
  .detail-grid{display:flex;flex-wrap:wrap;gap:14px;}
  .detail-grid strong{font-size:12.5px;color:var(--muted);}
  .detail-grid p{margin:4px 0 0;}
  .detail-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:6px 18px;margin:0;}
  .detail-list div{font-size:13px;}
  .detail-list dt{color:var(--muted);font-size:12px;}
  .detail-list dd{margin:0;}
  :focus-visible{outline:3px solid var(--focus);outline-offset:2px;border-radius:4px;}
  @media (prefers-reduced-motion: reduce){
    *,*::before,*::after{animation:none!important;transition:none!important;scroll-behavior:auto!important;}
  }
  @media (max-width:720px){
    .filter-groups{flex-direction:column;}
    .header-grid{flex-direction:column;}
  }
</style>
</head>
<body>
<div class="wrap">
<a class="skip-link" href="#main">Skip to main content</a>
__HEADER__
__BANNER__
<nav aria-label="Sections">
  <ul class="jump-links">
    <li><a href="#gym">Gym Health</a></li>
    <li><a href="#disagreement">Policy Disagreement</a></li>
    <li><a href="#failures">Failure Analysis</a></li>
    <li><a href="#costs">Cost Comparison</a></li>
    <li><a href="#model">Model Evaluation</a></li>
    <li><a href="#baselines">Allocator Baselines</a></li>
    <li><a href="#browser">Attempt Browser</a></li>
  </ul>
</nav>
__FILTERS__
<main id="main">
  <section aria-labelledby="heading-gym" id="gym">
    <h2 id="heading-gym">1 · Gym Health</h2>
    <div class="section-body" id="body-gym">__GYM__</div>
  </section>
  <section aria-labelledby="heading-disagreement" id="disagreement">
    <h2 id="heading-disagreement">2 · Policy Disagreement</h2>
    <div class="section-body" id="body-disagreement">__DISAGREEMENT__</div>
  </section>
  <section aria-labelledby="heading-failures" id="failures">
    <h2 id="heading-failures">3 · Failure Analysis</h2>
    <div class="section-body" id="body-failures">__FAILURES__</div>
  </section>
  <section aria-labelledby="heading-costs" id="costs">
    <h2 id="heading-costs">4 · Cost Comparison</h2>
    <div class="section-body" id="body-costs">__COSTS__</div>
  </section>
  <section aria-labelledby="heading-model" id="model">
    <h2 id="heading-model">5 · Model Evaluation</h2>
    <div class="section-body" id="body-model">__MODEL__</div>
  </section>
  <section aria-labelledby="heading-baselines" id="baselines">
    <h2 id="heading-baselines">6 · Allocator Baselines</h2>
    <div class="section-body" id="body-baselines">__BASELINES__</div>
  </section>
  <section aria-labelledby="heading-browser" id="browser">
    <h2 id="heading-browser">7 · Attempt Browser</h2>
    <div class="section-body" id="body-browser">__BROWSER__</div>
  </section>
</main>
<footer>
  <p class="muted">Pyreplab harness dashboard · self-contained file · no external resources.</p>
</footer>
</div>
<script>
"use strict";
/* The embedded payload escapes &lt; and &gt; so no script-terminating sequence can close this block early. */
var DATA = __DATA_JSON__;
var CAP = (DATA.config && typeof DATA.config.browser_cap === "number") ? DATA.config.browser_cap : 500;
var PALETTE = ["#1565C0","#E65100","#2E7D32","#6A1B9A","#00695C","#AD1457","#37474F","#5D4037","#4527A0","#1B5E20"];
var POLICY_COLORS = {"direct":"#1565C0","deliberate":"#E65100"};

/* ---- number helpers (mirror the Python aggregation functions) ---- */
function num(v){ return (typeof v === "number" && isFinite(v)) ? v : null; }
function mean(a){ if(!a.length) return null; var s=0,i; for(i=0;i<a.length;i++) s+=a[i]; return s/a.length; }
function popStd(a){ var n=a.length,i,d,s=0; if(!n) return null; if(n===1) return 0; var m=mean(a); for(i=0;i<n;i++){ d=a[i]-m; s+=d*d; } return Math.sqrt(s/n); }
function minMax(a){ if(!a.length) return [null,null]; var lo=a[0],hi=a[0],i; for(i=1;i<a.length;i++){ if(a[i]<lo) lo=a[i]; if(a[i]>hi) hi=a[i]; } return [lo,hi]; }
function totalTokens(row){
  var u = row.usage || {};
  var t = num(u.total_tokens);
  if (t !== null) return t;
  var s=0,k,v;
  for (k in u){ if (Object.prototype.hasOwnProperty.call(u,k)){ v=u[k];
    if (typeof v === "number" && isFinite(v) && v === Math.floor(v)) s += v; } }
  return s;
}
function policyColor(p){
  if (p === null || p === undefined) return "#607D8B";
  if (Object.prototype.hasOwnProperty.call(POLICY_COLORS,p)) return POLICY_COLORS[p];
  var idx=0,i,h=0;
  for(i=0;i<String(p).length;i++){ h += String(p).charCodeAt(i)*(i+1); }
  idx = h % PALETTE.length;
  return PALETTE[idx];
}
function fmtPct(v){ return v===null||v===undefined ? "—" : (v*100).toFixed(1)+"%"; }
function fmtNum(v,d){ d = d===undefined?1:d; return (v===null||v===undefined) ? "—" : v.toFixed(d); }
function fmtInt(v){ return (v===null||v===undefined) ? "—" : String(Math.round(v)); }

/* ---- filters ---- */
var state = {family:{}, difficulty:{}, policy:{}};
function initState(){
  ["family","difficulty","policy"].forEach(function(dim){
    state[dim] = {};
    (DATA.filters[dim] || []).forEach(function(v){ state[dim][v] = true; });
  });
}
function rowMatches(r){
  return state.family[r.family] !== false
      && state.difficulty[r.difficulty] !== false
      && state.policy[r.policy_id] !== false;
}
function filteredRows(){ return (DATA.rows||[]).filter(rowMatches); }

/* ---- aggregations (mirror the Python functions) ---- */
function aggGym(rows){
  var total=rows.length, taskSet={}, polSet={}, famSet={}, paired=0, i, r;
  for(i=0;i<total;i++){ r=rows[i]; taskSet[r.task_id]=1; polSet[r.policy_id]=1; famSet[r.family]=1; }
  var tasks = Object.keys(taskSet);
  for(i=0;i<tasks.length;i++){
    var seen={};
    rows.forEach(function(x){ if(x.task_id===tasks[i]) seen[x.policy_id]=1; });
    if (Object.keys(seen).length >= 2) paired++;
  }
  var success=0, tokens=[];
  var cells = {};
  rows.forEach(function(r){
    if (r.verified_success) success++;
    tokens.push(totalTokens(r));
    var key = r.family + "\u0000" + r.policy_id;
    var cell = cells[key] || (cells[key]={n:0,success:0});
    cell.n++; if (r.verified_success) cell.success++;
  });
  var families = Object.keys(famSet).sort();
  var policies = Object.keys(polSet).sort();
  var familyPolicy = [];
  families.forEach(function(f){
    policies.forEach(function(p){
      var cell = cells[f + "\u0000" + p];
      if (!cell) return;
      familyPolicy.push({family:f,policy:p,n:cell.n,success:cell.success,
        success_rate: cell.n ? cell.success/cell.n : null});
    });
  });
  return {total_rows:total, total_tasks:tasks.length, paired_tasks:paired,
    task_coverage: tasks.length ? paired/tasks.length : null,
    success_count:success,
    overall_success_rate: total ? success/total : null,
    avg_total_tokens: tokens.length ? mean(tokens) : null,
    disagreement_rate: aggDisagreement(rows).disagreement_rate,
    policies:policies, families:families, family_policy:familyPolicy};
}
function pairPolicies(rows){
  var counts = {};
  rows.forEach(function(r){ counts[r.policy_id]=(counts[r.policy_id]||0)+1; });
  var arr = Object.keys(counts).map(function(k){ return [k,counts[k]]; });
  arr.sort(function(x,y){ return (y[1]-x[1]) || (x[0] < y[0] ? -1 : x[0] > y[0] ? 1 : 0); });
  var a = Object.prototype.hasOwnProperty.call(counts,"direct") ? "direct" : (arr.length ? arr[0][0] : null);
  var b = null;
  if (Object.prototype.hasOwnProperty.call(counts,"deliberate") && a !== "deliberate"){ b = "deliberate"; }
  else {
    var rest = arr.filter(function(p){ return p[0] !== a; });
    b = rest.length ? rest[0][0] : null;
  }
  return [a,b];
}
function cellClass(color){ return color==="#1565C0" ? "cell-a" : color==="#E65100" ? "cell-b" : "cell-neutral"; }
function taskPolicyOutcome(rows, taskId, policy){
  if (taskId===null||taskId===undefined||policy===null||policy===undefined) return null;
  var c = rows.filter(function(r){ return r.task_id===taskId && r.policy_id===policy; });
  c.sort(function(a,b){ var x=a.attempt_id||"", y=b.attempt_id||""; return x<y?-1:x>y?1:0; });
  return c.length ? !!c[0].verified_success : null;
}
function aggDisagreement(rows){
  var pair = pairPolicies(rows), a=pair[0], b=pair[1];
  var tasks={}; rows.forEach(function(r){ tasks[r.task_id]=1; });
  var taskIds=Object.keys(tasks);
  var matrix={both_ok:0,a_only:0,b_only:0,both_fail:0};
  var famCounts={}, paired=0, unpaired=0;
  taskIds.forEach(function(tid){
    var present={}, family=null;
    rows.forEach(function(r){ if(r.task_id===tid){ present[r.policy_id]=1; family=r.family; } });
    if (!(a in present) || !(b in present)){ unpaired++; return; }
    paired++;
    var cell = famCounts[family] || (famCounts[family]={paired:0,both_ok:0,a_only:0,b_only:0,both_fail:0});
    cell.paired++;
    var oa = taskPolicyOutcome(rows,tid,a), ob = taskPolicyOutcome(rows,tid,b);
    if (oa===null||ob===null) return;
    if (oa && ob){ matrix.both_ok++; cell.both_ok++; }
    else if (oa && !ob){ matrix.a_only++; cell.a_only++; }
    else if (!oa && ob){ matrix.b_only++; cell.b_only++; }
    else { matrix.both_fail++; cell.both_fail++; }
  });
  var disagreement = matrix.a_only + matrix.b_only;
  var byFamily = Object.keys(famCounts).sort().map(function(f){
    var c = famCounts[f];
    c.family=f; c.disagreement = c.a_only + c.b_only;
    c.disagreement_rate = c.paired ? c.disagreement/c.paired : null;
    return c;
  });
  return {policy_a:a, policy_b:b, matrix:matrix,
    disagreement_count:disagreement,
    disagreement_rate: paired ? disagreement/paired : null,
    paired_tasks:paired, unpaired_tasks:unpaired, total_tasks:taskIds.length,
    by_family:byFamily};
}
function aggFailures(rows){
  var total=rows.length, failCount=0, byFamily={}, byCode={};
  rows.forEach(function(r){
    var f = r.family;
    byFamily[f] = byFamily[f] || {total:0,failures:0};
    byFamily[f].total++;
    if (!r.verified_success){
      failCount++;
      byFamily[f].failures++;
      if (r.failure_code !== null && r.failure_code !== undefined){
        byCode[r.failure_code] = (byCode[r.failure_code]||0)+1;
      }
    }
  });
  var familyRows = Object.keys(byFamily).sort().map(function(f){
    var c=byFamily[f];
    return {family:f,total:c.total,failures:c.failures,
      failure_rate: c.total ? c.failures/c.total : null};
  });
  var codeRows = Object.keys(byCode).sort(function(x,y){
    return (byCode[y]-byCode[x]) || (x<y?-1:x>y?1:0);
  }).map(function(code){
    var c=byCode[code];
    return {code:code,count:c,
      share_of_failures: failCount ? c/failCount : null,
      failure_rate: total ? c/total : null};
  });
  return {total_rows:total, failure_count:failCount,
    failure_rate: total ? failCount/total : null,
    by_family:familyRows, by_code:codeRows};
}
function aggCosts(rows){
  var groups = {};
  rows.forEach(function(r){
    var key = r.family + "\u0000" + r.policy_id;
    (groups[key] = groups[key] || []).push(r);
  });
  var out = [];
  Object.keys(groups).sort().forEach(function(key){
    var parts = key.split("\u0000"), members=groups[key];
    var bundle = function(fn){
      var vals=members.map(fn), mm=minMax(vals);
      return {mean:mean(vals), std:popStd(vals), min:mm[0], max:mm[1]};
    };
    out.push({family:parts[0], policy:parts[1], n:members.length,
      total_tokens: bundle(function(r){return totalTokens(r);}),
      tool_calls: bundle(function(r){return r.tool_call_count||0;}),
      assistant_messages: bundle(function(r){return r.assistant_message_count||0;})});
  });
  return {rows:out};
}

/* ---- DOM helpers: nodes are built with textContent/createElement only ---- */
function h(tag, cls, text){ var e=document.createElement(tag); if(cls) e.className=cls; if(text!==undefined&&text!==null) e.textContent=String(text); return e; }
function thc(text){ return h("th",null,text); }
function tdc(text){ var e=h("td"); if(text!==undefined&&text!==null) e.textContent=String(text); return e; }
function clearNode(n){ while(n.firstChild) n.removeChild(n.firstChild); }
function cellCls(ok){ return ok ? "cell-ok" : "cell-bad"; }
function bar(value,color){
  var wrap=document.createElement("span"); wrap.className="cell-bar";
  var outer=document.createElement("span"); outer.className="bar"; outer.setAttribute("aria-hidden","true");
  var fill=document.createElement("span"); fill.className="bar-fill";
  fill.style.width = (Math.max(0,Math.min(100,(value||0)*100))).toFixed(1)+"%";
  fill.style.backgroundColor = color; outer.appendChild(fill);
  wrap.appendChild(outer); wrap.appendChild(document.createTextNode(" "+fmtPct(value)));
  return wrap;
}
function dot(color){
  var s=document.createElement("span"); s.className="dot"; s.style.backgroundColor=color;
  s.setAttribute("aria-hidden","true");
  return s;
}

/* ---- section renderers ---- */
function renderGym(rows){
  var g = aggGym(rows), body = document.getElementById("body-gym");
  clearNode(body);
  var kpi = function(label,value,note,cue){
    var d=h("div","kpi");
    d.appendChild(h("span","kpi-label",label));
    d.appendChild(h("span","kpi-value",value));
    d.appendChild(h("span","kpi-note",(note||"")+(cue||"")));
    return d;
  };
  var kpis=h("div","kpis");
  kpis.appendChild(kpi("Overall success",fmtPct(g.overall_success_rate),"of attempts", g.overall_success_rate!==null&&g.overall_success_rate>=0.5?" ✓":" ✗"));
  kpis.appendChild(kpi("Task coverage",fmtPct(g.task_coverage),"tasks with both policies",""));
  kpis.appendChild(kpi("Paired disagreement",fmtPct(g.disagreement_rate),"of paired tasks",""));
  kpis.appendChild(kpi("Avg total tokens",fmtNum(g.avg_total_tokens,0),"per attempt",""));
  body.appendChild(kpis);

  var card=h("div","card");
  card.appendChild(h("h3",null,"Success by family × policy"));
  var table=h("table","data"), thead=h("thead"), tbody=h("tbody");
  var hr=h("tr");
  ["Family","Policy","Attempts","Success","Success rate","Distribution"].forEach(function(c){ var t=thc(c); t.setAttribute("scope","col"); hr.appendChild(t); });
  thead.appendChild(hr); table.appendChild(thead);
  if(!g.family_policy.length){
    var tr=h("tr"); var td=tdc("No verified attempts to aggregate."); td.colSpan=6; td.className="empty"; tr.appendChild(td); tbody.appendChild(tr);
  }
  g.family_policy.forEach(function(cell){
    var tr=h("tr");
    tr.appendChild(tdc(cell.family));
    var polTd=h("td"); polTd.appendChild(dot(policyColor(cell.policy))); polTd.appendChild(document.createTextNode(" "+String(cell.policy)));
    tr.appendChild(polTd);
    tr.appendChild(tdc(cell.n)); tr.appendChild(tdc(cell.success));
    tr.appendChild(tdc(fmtPct(cell.success_rate)+((cell.success_rate!==null&&cell.success_rate>=0.5)?" ✓":" ✗")));
    var barTd=h("td"); barTd.appendChild(bar(cell.success_rate,policyColor(cell.policy))); tr.appendChild(barTd);
    tbody.appendChild(tr);
  });
  table.appendChild(tbody);
  var wrap=h("div","table-scroll"); wrap.appendChild(table);
  card.appendChild(wrap); body.appendChild(card);
}

function renderDisagreement(rows){
  var d = aggDisagreement(rows), body = document.getElementById("body-disagreement");
  clearNode(body);
  var a=d.policy_a, b=d.policy_b;
  var win=h("p","muted");
  win.appendChild(dot(policyColor(a)));
  win.appendChild(document.createTextNode(" Compared policies: "+(a||"—")+" vs "));
  win.appendChild(dot(policyColor(b)));
  win.appendChild(document.createTextNode(" "+(b||"—")+". "));
  win.appendChild(document.createTextNode((a||"—")+"-only wins: "));
  var st=document.createElement("strong"); st.textContent=String(d.matrix.a_only); win.appendChild(st);
  win.appendChild(document.createTextNode(" · "+(b||"—")+"-only wins: "));
  st=document.createElement("strong"); st.textContent=String(d.matrix.b_only); win.appendChild(st);
  win.appendChild(document.createTextNode("."));
  body.appendChild(win);
  if (!d.paired_tasks){
    var note=h("div","state-note"); note.setAttribute("role","status");
    note.textContent="No paired tasks to compare — the dataset needs at least two policies run on the same task.";
    body.appendChild(note);
    return;
  }
  var m=d.matrix;
  var cells=[["Both succeed",m.both_ok,"cell-ok"],[(a||"—")+" succeeds only",m.a_only,cellClass(policyColor(a))],
             [(b||"—")+" succeeds only",m.b_only,cellClass(policyColor(b))],["Both fail",m.both_fail,"cell-bad"]];
  var card=h("div","card");
  card.appendChild(h("h3",null,"2×2 paired outcome matrix"));
  var grid=h("div","matrix-grid");
  var mt=h("table","matrix");
  var mtb=h("tbody");
  cells.forEach(function(c){
    var tr=h("tr"); tr.appendChild(h("td","label",c[0]));
    var td=h("td","num "+c[2]); td.textContent=String(c[1]);
    tr.appendChild(td); mtb.appendChild(tr);
  });
  mt.appendChild(mtb); grid.appendChild(mt);
  var p=h("p","muted note");
  p.appendChild(document.createTextNode("Paired by task_id: one representative attempt per policy (first by attempt id). A task counts once. "));
  var st2=document.createElement("strong"); st2.textContent=String(d.paired_tasks); p.appendChild(st2);
  p.appendChild(document.createTextNode(" paired task(s) out of "+String(d.total_tasks)+"."));
  grid.appendChild(p); card.appendChild(grid); body.appendChild(card);

  var card2=h("div","card");
  card2.appendChild(h("h3",null,"Disagreement by family"));
  var t=h("table","data"), th0=h("thead"), tb0=h("tbody");
  var hr2=h("tr"); ["Family","Paired tasks","Both ✓",(a||"—")+" only ✓",(b||"—")+" only ✓","Both ✗","Disagreement","Disagreement rate"].forEach(function(c){ var x=thc(c); x.setAttribute("scope","col"); hr2.appendChild(x); });
  th0.appendChild(hr2); t.appendChild(th0);
  if(!d.by_family.length){ var tr0=h("tr"); var td0=tdc("No paired families."); td0.colSpan=8; td0.className="empty"; tr0.appendChild(td0); tb0.appendChild(tr0); }
  d.by_family.forEach(function(f){
    var tr=h("tr");
    [f.family,f.paired,f.both_ok,f.a_only,f.b_only,f.both_fail,f.disagreement,fmtPct(f.disagreement_rate)].forEach(function(v){ tr.appendChild(tdc(v)); });
    tb0.appendChild(tr);
  });
  t.appendChild(tb0);
  var w=h("div","table-scroll"); w.appendChild(t);
  card2.appendChild(w); body.appendChild(card2);
}

function renderFailures(rows){
  var f=aggFailures(rows), body=document.getElementById("body-failures");
  clearNode(body);
  var lead=h("p","muted");
  lead.appendChild(document.createTextNode("Overall failure rate: "));
  var st=document.createElement("strong"); st.textContent=fmtPct(f.failure_rate); lead.appendChild(st);
  lead.appendChild(document.createTextNode(" ("+String(f.failure_count)+" of "+String(f.total_rows)+" attempts)."));
  body.appendChild(lead);

  var card=h("div","card"); card.appendChild(h("h3",null,"Failures by family"));
  var t=h("table","data"), th0=h("thead"), tb0=h("tbody");
  var hr=h("tr"); ["Family","Attempts","Failures","Failure rate","Distribution"].forEach(function(c){ var x=thc(c); x.setAttribute("scope","col"); hr.appendChild(x); });
  th0.appendChild(hr); t.appendChild(th0);
  if(!f.by_family.length){ var tr=h("tr"); var td=tdc("No attempts."); td.colSpan=5; td.className="empty"; tr.appendChild(td); tb0.appendChild(tr); }
  f.by_family.forEach(function(r){
    var tr=h("tr"); tr.appendChild(tdc(r.family)); tr.appendChild(tdc(r.total)); tr.appendChild(tdc(r.failures)); tr.appendChild(tdc(fmtPct(r.failure_rate)));
    var b=h("td"); b.appendChild(bar(r.failure_rate,"#C62828")); tr.appendChild(b); tb0.appendChild(tr);
  });
  t.appendChild(tb0); var w=h("div","table-scroll"); w.appendChild(t); card.appendChild(w); body.appendChild(card);

  var card2=h("div","card"); card2.appendChild(h("h3",null,"Failures by code"));
  var t2=h("table","data"), th1=h("thead"), tb1=h("tbody");
  var hr2=h("tr"); ["Failure code","Count","Share of failures","Failure rate"].forEach(function(c){ var x=thc(c); x.setAttribute("scope","col"); hr2.appendChild(x); });
  th1.appendChild(hr2); t2.appendChild(th1);
  if(!f.by_code.length){ var tr2=h("tr"); var td2=tdc("No verified failures recorded."); td2.colSpan=4; td2.className="empty"; tr2.appendChild(td2); tb1.appendChild(tr2); }
  f.by_code.forEach(function(r){
    var tr=h("tr"); var code=document.createElement("code"); code.textContent=r.code;
    var td=h("td"); td.appendChild(code); tr.appendChild(td);
    tr.appendChild(tdc(r.count)); tr.appendChild(tdc(fmtPct(r.share_of_failures))); tr.appendChild(tdc(fmtPct(r.failure_rate)));
    tb1.appendChild(tr);
  });
  t2.appendChild(tb1); var w2=h("div","table-scroll"); w2.appendChild(t2); card2.appendChild(w2); body.appendChild(card2);
}

function renderCosts(rows){
  var c=aggCosts(rows), body=document.getElementById("body-costs");
  clearNode(body);
  var card=h("div","card"); card.appendChild(h("h3",null,"Cost comparison by family × policy"));
  var t=h("table","data"), th0=h("thead"), tb0=h("tbody");
  var hr=h("tr");
  ["Family","Policy","n","Total tokens mean ± std","Tokens min–max","Tool calls mean ± std","Tools min–max","Messages mean ± std","Messages min–max"].forEach(function(c2){ var x=thc(c2); x.setAttribute("scope","col"); hr.appendChild(x); });
  th0.appendChild(hr); t.appendChild(th0);
  if(!c.rows.length){ var tr=h("tr"); var td=tdc("No cost data to aggregate."); td.colSpan=9; td.className="empty"; tr.appendChild(td); tb0.appendChild(tr); }
  c.rows.forEach(function(r){
    var tr=h("tr");
    tr.appendChild(tdc(r.family));
    var pt=h("td"); pt.appendChild(dot(policyColor(r.policy))); pt.appendChild(document.createTextNode(" "+String(r.policy))); tr.appendChild(pt);
    tr.appendChild(tdc(r.n));
    var hasRange = r.n > 1;
    var tokStd = hasRange ? fmtNum(r.total_tokens.std) : "—";
    var tokMM = hasRange ? fmtInt(r.total_tokens.min)+"–"+fmtInt(r.total_tokens.max) : "—";
    var toolStd = hasRange ? fmtNum(r.tool_calls.std) : "—";
    var toolMM = hasRange ? fmtInt(r.tool_calls.min)+"–"+fmtInt(r.tool_calls.max) : "—";
    var msgStd = hasRange ? fmtNum(r.assistant_messages.std) : "—";
    var msgMM = hasRange ? fmtInt(r.assistant_messages.min)+"–"+fmtInt(r.assistant_messages.max) : "—";
    tr.appendChild(tdc(fmtNum(r.total_tokens.mean)+(hasRange?" ± "+tokStd:"")));
    tr.appendChild(tdc(tokMM));
    tr.appendChild(tdc(fmtNum(r.tool_calls.mean)+(hasRange?" ± "+toolStd:"")));
    tr.appendChild(tdc(toolMM));
    tr.appendChild(tdc(fmtNum(r.assistant_messages.mean)+(hasRange?" ± "+msgStd:"")));
    tr.appendChild(tdc(msgMM));
    tb0.appendChild(tr);
  });
  t.appendChild(tb0); var w=h("div","table-scroll"); w.appendChild(t); card.appendChild(w); body.appendChild(card);
}

function renderModelPolicy(){
  var wrap=document.getElementById("model-policy-wrap");
  if(!wrap) return;
  var rows=(DATA.model && DATA.model.status==="present" && DATA.model.per_policy) ? DATA.model.per_policy : [];
  var filtered=rows.filter(function(r){ return state.policy[r.policy] !== false; });
  var t=h("table","data"), th0=h("thead"), tb0=h("tbody");
  var hr=h("tr"); ["Policy","Split","n","Log loss","Brier","Accuracy","ECE","Posterior std"].forEach(function(c){ var x=thc(c); x.setAttribute("scope","col"); hr.appendChild(x); });
  th0.appendChild(hr); t.appendChild(th0);
  if(!filtered.length){ var tr=h("tr"); var td=tdc("No per-policy metrics for the selected policies."); td.colSpan=8; td.className="empty"; tr.appendChild(td); tb0.appendChild(tr); }
  filtered.forEach(function(r){
    var tr=h("tr");
    [r.policy, r.split, r.n, fmtNum(r.log_loss,4), fmtNum(r.brier,4), fmtPct(r.accuracy_05), fmtNum(r.ece,4), fmtNum(r.mean_posterior_std,4)].forEach(function(v){ tr.appendChild(tdc(v)); });
    tb0.appendChild(tr);
  });
  t.appendChild(tb0);
  clearNode(wrap); wrap.appendChild(t);
}

function renderBrowser(rows){
  var total=rows.length, shown=rows.slice(0,CAP);
  var body=document.getElementById("body-browser");
  var count=document.getElementById("browser-count");
  if(count){ count.textContent="Showing "+String(shown.length)+" of "+String(total)+" attempts (capped at "+String(CAP)+" rows)."; }
  var tbody=document.getElementById("browser-tbody");
  if(!tbody) return;
  clearNode(tbody);
  if(!shown.length){
    var tr=h("tr"); var td=tdc("No attempts match the current filters."); td.colSpan=12; td.className="empty"; tr.appendChild(td); tbody.appendChild(tr);
    return;
  }
  shown.forEach(function(r,index){
    var tr=h("tr");
    var tdId=h("td"); var code=document.createElement("code"); code.textContent=String(r.task_id); tdId.appendChild(code); tr.appendChild(tdId);
    tr.appendChild(tdc(r.family)); tr.appendChild(tdc(r.difficulty||"—")); tr.appendChild(tdc(r.policy_id)); tr.appendChild(tdc(r.split||"—"));
    var out=h("td"); var span=h("span",cellCls(r.verified_success), r.verified_success?"✓":"✗");
    out.appendChild(span); out.appendChild(document.createTextNode(r.verified_success?" success":" fail")); tr.appendChild(out);
    tr.appendChild(tdc(r.failure_code||"—")); tr.appendChild(tdc(r.verifier_id||"—"));
    tr.appendChild(tdc(totalTokens(r))); tr.appendChild(tdc(r.tool_call_count||0)); tr.appendChild(tdc(r.assistant_message_count||0));
    var tdBtn=h("td");
    var btn=h("button","btn-link","Details");
    btn.type="button"; btn.setAttribute("data-detail-toggle",""); btn.setAttribute("aria-expanded","false"); btn.setAttribute("aria-controls","detail-"+index);
    tdBtn.appendChild(btn); tr.appendChild(tdBtn);
    tbody.appendChild(tr);
    tbody.appendChild(detailRow(r,index));
  });
}
function detailRow(r,index){
  var tr=h("tr","detail-row hidden"); tr.id="detail-"+index;
  var td=h("td"); td.colSpan=12;
  var grid=h("div","detail-grid");
  var d0=h("div");
  d0.appendChild(h("strong",null,"Prompt preview"));
  var p=h("p",null,r.prompt_preview||"—"); d0.appendChild(p); grid.appendChild(d0);
  var dl=document.createElement("dl"); dl.className="detail-list";
  var items=[
    ["Template",r.template_id||"—"],["Generator version",r.generator_version||"—"],["Seed",String(r.seed)],
    ["Policy version",r.policy_version||"—"],["Verifier version",r.verifier_version||"—"],["Final text length",String(r.final_text_length)],
    ["Usage", (function(){ var u=r.usage||{},ks=Object.keys(u).sort(),parts=[]; ks.forEach(function(k){ parts.push(k+": "+String(u[k])); }); return parts.join(", ")||"—"; })()],
    ["Metadata", (function(){ var m=r.metadata||{},ks=Object.keys(m).sort(),parts=[]; ks.forEach(function(k){ parts.push(k+": "+String(m[k])); }); return parts.join(", ")||"—"; })()]
  ];
  items.forEach(function(it){
    var w=document.createElement("div");
    var dt=document.createElement("dt"); dt.textContent=it[0];
    var dd=document.createElement("dd"); dd.textContent=String(it[1]);
    w.appendChild(dt); w.appendChild(dd); dl.appendChild(w);
  });
  grid.appendChild(dl); td.appendChild(grid); tr.appendChild(td);
  return tr;
}

/* ---- wiring ---- */
function updateLiveCounts(rows){
  var f=document.getElementById("filter-count");
  if(f) f.textContent="Showing "+String(rows.length)+" of "+String(DATA.rows.length)+" verified attempts.";
}
function renderAll(){
  var rows=filteredRows();
  renderGym(rows); renderDisagreement(rows); renderFailures(rows); renderCosts(rows);
  renderBrowser(rows); renderModelPolicy(); updateLiveCounts(rows);
}
function wireFilters(){
  var inputs=document.querySelectorAll("input[type=checkbox][data-filter]");
  Array.prototype.forEach.call(inputs,function(cb){
    cb.addEventListener("change",function(){
      state[cb.dataset.filter][cb.value]=cb.checked;
      renderAll();
    });
  });
  var reset=document.getElementById("filter-reset");
  if(reset){
    reset.addEventListener("click",function(){
      ["family","difficulty","policy"].forEach(function(dim){
        (DATA.filters[dim]||[]).forEach(function(v){ state[dim][v]=true; });
      });
      Array.prototype.forEach.call(document.querySelectorAll("input[type=checkbox][data-filter]"),function(cb){ cb.checked=true; });
      renderAll();
    });
  }
}
document.addEventListener("click",function(ev){
  var btn = ev.target && ev.target.closest ? ev.target.closest("[data-detail-toggle]") : null;
  if(!btn) return;
  var tr = btn.closest("tr");
  var next = tr.nextElementSibling;
  if(next && next.classList.contains("detail-row")){
    var hidden = next.classList.toggle("hidden");
    btn.setAttribute("aria-expanded", hidden ? "false" : "true");
  }
});
function init(){
  initState(); wireFilters(); renderAll();
}
if (document.readyState === "loading"){ document.addEventListener("DOMContentLoaded",init); } else { init(); }
</script>
</body>
</html>
"""


# The __main__ guard lives at the true end of the module, after _TEMPLATE (and
# every other definition) is bound, so `python -m pyreplab_harness.dashboard`
# never calls main() while the module body is still mid-execution.
if __name__ == "__main__":
    raise SystemExit(main())
